// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sat Mar 28 14:06:10 2020

i2s_master i2s_master_inst
(
	.clk_12m(clk_12m_sig) ,	// input  clk_12m_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.load_o(load_o_sig) ,	// output  load_o_sig
	.adcdat_pl_o(adcdat_pl_o_sig) ,	// output [15:0] adcdat_pl_o_sig
	.adcdat_pr_o(adcdat_pr_o_sig) ,	// output [15:0] adcdat_pr_o_sig
	.dacdat_pl_i(dacdat_pl_i_sig) ,	// input [15:0] dacdat_pl_i_sig
	.dacdat_pr_i(dacdat_pr_i_sig) ,	// input [15:0] dacdat_pr_i_sig
	.dacdat_s_o(dacdat_s_o_sig) ,	// output  dacdat_s_o_sig
	.bclk_o(bclk_o_sig) ,	// output  bclk_o_sig
	.ws_o(ws_o_sig) ,	// output  ws_o_sig
	.adcdat_s_i(adcdat_s_i_sig) 	// input  adcdat_s_i_sig
);

